-- Supabase SQL Schema for Midas Markets
-- Paste and run this in the Supabase SQL Editor

-- 1. Reviews Table
CREATE TABLE IF NOT EXISTS reviews (
  id bigint generated by default as identity primary key,
  type text not null,
  name text not null,
  text text not null,
  stars integer not null,
  status text default 'pending',
  admin_response text default null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Suggestions Table
CREATE TABLE IF NOT EXISTS suggestions (
  id bigint generated by default as identity primary key,
  name text,
  text text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Emails (Waitlist) Table
CREATE TABLE IF NOT EXISTS emails (
  id bigint generated by default as identity primary key,
  email text not null unique,
  name text,
  source text default 'waitlist',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Analytics Table
CREATE TABLE IF NOT EXISTS analytics (
  id bigint generated by default as identity primary key,
  event_type text not null,
  event_target text not null,
  referrer text,
  user_agent text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Proofs Table
CREATE TABLE IF NOT EXISTS proofs (
  id bigint generated by default as identity primary key,
  filename text,
  title text,
  subtitle text,
  badge text,
  is_red boolean,
  details text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. FAQs Table
CREATE TABLE IF NOT EXISTS faqs (
  id bigint generated by default as identity primary key,
  question text,
  answer text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 7. Settings Table
CREATE TABLE IF NOT EXISTS settings (
  id bigint generated by default as identity primary key,
  key text unique not null,
  value text
);
